server:
  port: 10101

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    mongodb:
      uri: #uri
  session:
    timeout: 600
    store-type: mongodb
    mongodb:
      collection-name: session

logging.level:
  #  root: DEBUG
  org.springframework:
    security: DEBUG
    data:
      mongodb: DEBUG
    # session: DEBUG
    web.server.adapter.HttpWebHandlerAdapter: DEBUG

