server:
  port: 10101

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    mongodb:
      uri: #uri

logging.level:
  #  root: DEBUG
  org.springframework:
    security: DEBUG
    data:
      mongodb: DEBUG
    # session: DEBUG
    web.server.adapter.HttpWebHandlerAdapter: DEBUG
